/* Split scaffold fragment. Real code is unity-included by scaffold.c; direct compilation emits only the anchor below. */

#if defined(LIMITLESS_SCAFFOLD_ELF_PE_PE_OUTPUT)
#if defined(LIMITLESS_X64_UEFI_KERNEL) && LIMITLESS_X64_UEFI_KERNEL
    write_string("[x64] pe-J1 header parse ");
    write_dec_u32(pe_j1_parse);
    write_string(" machine ");
    write_hex_u32((u32)pe_j1_header.machine);
    write_string(" sections ");
    write_dec_u32((u32)pe_j1_header.number_of_sections);
    write_string(" entry ");
    write_hex_u32(pe_j1_header.address_of_entry_point);
    write_string(" image-base ");
    write_hex_u64(pe_j1_header.image_base);
    write_string(" image-size ");
    write_hex_u32(pe_j1_header.size_of_image);
    write_string(" headers ");
    write_hex_u32(pe_j1_header.size_of_headers);
    write_string(" optional ");
    write_dec_u32((u32)pe_j1_header.size_of_optional_header);
    write_string("/");
    write_hex_u32((u32)pe_j1_header.optional_magic);
    write_string(" peoff ");
    write_hex_u32(pe_j1_header.pe_offset);
    write_string(" dirs ");
    write_dec_u32(pe_j1_header.number_of_rva_and_sizes);
    write_string(" deny ");
    write_dec_u32(pe_j1_bad_magic);
    write_string("/");
    write_dec_u32(pe_j1_bad_magic_error);
    write_string(" ");
    write_dec_u32(pe_j1_bad_machine);
    write_string("/");
    write_dec_u32(pe_j1_bad_machine_error);
    write_string(" ");
    write_dec_u32(pe_j1_bad_optional);
    write_string("/");
    write_dec_u32(pe_j1_bad_optional_error);
    write_string(" positive ");
    write_dec_u32(pe_j1_positive);
    write_line("");
    write_string("[x64] pe-J2 sections parse ");
    write_dec_u32(pe_j2_parse);
    write_string(" count ");
    write_dec_u32(pe_j2_summary.section_count);
    write_string(" names ");
    write_dec_u32(pe_j2_names_match);
    write_string(" attrs ");
    write_dec_u32(pe_j2_attrs_match);
    write_string(" ranges ");
    write_dec_u32(pe_j2_ranges_match);
    write_string(" text ");
    write_hex_u32(pe_j2_sections[0].virtual_address);
    write_string("/");
    write_hex_u32(pe_j2_sections[0].virtual_size);
    write_string("/");
    write_hex_u32(pe_j2_sections[0].pointer_to_raw_data);
    write_string("/");
    write_hex_u32(pe_j2_sections[0].size_of_raw_data);
    write_string("/");
    write_hex_u32(pe_j2_sections[0].characteristics);
    write_string(" rdata ");
    write_hex_u32(pe_j2_sections[1].virtual_address);
    write_string("/");
    write_hex_u32(pe_j2_sections[1].virtual_size);
    write_string("/");
    write_hex_u32(pe_j2_sections[1].pointer_to_raw_data);
    write_string("/");
    write_hex_u32(pe_j2_sections[1].size_of_raw_data);
    write_string("/");
    write_hex_u32(pe_j2_sections[1].characteristics);
    write_string(" data ");
    write_hex_u32(pe_j2_sections[2].virtual_address);
    write_string("/");
    write_hex_u32(pe_j2_sections[2].virtual_size);
    write_string("/");
    write_hex_u32(pe_j2_sections[2].pointer_to_raw_data);
    write_string("/");
    write_hex_u32(pe_j2_sections[2].size_of_raw_data);
    write_string("/");
    write_hex_u32(pe_j2_sections[2].characteristics);
    write_string(" prot ");
    write_dec_u32(pe_j2_sections[0].prot_flags);
    write_string("/");
    write_dec_u32(pe_j2_sections[1].prot_flags);
    write_string("/");
    write_dec_u32(pe_j2_sections[2].prot_flags);
    write_string(" totals ");
    write_hex_u64(pe_j2_summary.total_raw_bytes);
    write_string("/");
    write_hex_u64(pe_j2_summary.total_virtual_bytes);
    write_string(" range ");
    write_hex_u32(pe_j2_summary.first_virtual_address);
    write_string("/");
    write_hex_u32(pe_j2_summary.max_virtual_end);
    write_string(" flags ");
    write_dec_u32(pe_j2_summary.executable_count);
    write_string("/");
    write_dec_u32(pe_j2_summary.readable_count);
    write_string("/");
    write_dec_u32(pe_j2_summary.writable_count);
    write_string("/");
    write_dec_u32(pe_j2_summary.code_count);
    write_string("/");
    write_dec_u32(pe_j2_summary.initialized_data_count);
    write_string("/");
    write_dec_u32(pe_j2_summary.uninitialized_data_count);
    write_string(" checksum ");
    write_hex_u32(pe_j2_summary.name_checksum);
    write_string(" deny ");
    write_dec_u32(pe_j2_capacity);
    write_string("/");
    write_dec_u32(pe_j2_capacity_error);
    write_string(" ");
    write_dec_u32(pe_j2_truncated);
    write_string("/");
    write_dec_u32(pe_j2_truncated_error);
    write_string(" positive ");
    write_dec_u32(pe_j2_positive);
    write_line("");
    write_string("[x64] pe-J3 section-map ");
    write_dec_u32(pe_j3_map);
    write_string(" sections ");
    write_dec_u32(pe_j3_result.mapped_count);
    write_string(" bytes ");
    write_hex_u64(pe_j3_result.total_map_bytes);
    write_string(" file ");
    write_hex_u64(pe_j3_result.total_file_bytes);
    write_string(" bss ");
    write_hex_u64(pe_j3_result.total_bss_bytes);
    write_string(" base ");
    write_hex_u64(pe_j3_result.actual_base);
    write_string(" text-pte ");
    write_dec_u32(pe_j3_text_pte);
    write_string(" text-prot ");
    write_hex_u32(pe_j3_text_prot);
    write_string(" rdata-pte ");
    write_dec_u32(pe_j3_rdata_pte);
    write_string(" rdata-prot ");
    write_hex_u32(pe_j3_rdata_prot);
    write_string(" data-pte ");
    write_dec_u32(pe_j3_data_pte);
    write_string(" data-prot ");
    write_hex_u32(pe_j3_data_prot);
    write_string(" first ");
    write_hex_u32(pe_j3_text_first);
    write_string("/");
    write_hex_u32(pe_j3_rdata_first);
    write_string("/");
    write_hex_u32(pe_j3_data_first);
    write_string(" bss-zero ");
    write_dec_u32(pe_j3_bss_zero);
    write_string(" source ");
    write_hex_u32(pe_j3_result.source_checksum);
    write_string(" mapped ");
    write_hex_u32(pe_j3_result.mapped_checksum);
    write_string(" denied ");
    write_dec_u32(pe_j3_denied);
    write_string(" err ");
    write_dec_u32(pe_j3_denied_error);
    write_string(" cleanup ");
    write_dec_u32(pe_j3_cleanup);
    write_string(" positive ");
    write_dec_u32(pe_j3_positive);
    write_line("");
    write_string("[x64] pe-J4 reloc ");
    write_dec_u32(pe_j4_apply);
    write_string(" blocks ");
    write_dec_u32(pe_j4_result.block_count);
    write_string(" entries ");
    write_dec_u32(pe_j4_result.entry_count);
    write_string(" applied ");
    write_dec_u32(pe_j4_result.applied_count);
    write_string(" skipped ");
    write_dec_u32(pe_j4_result.skipped_count);
    write_string(" preferred ");
    write_hex_u64(pe_j4_result.preferred_base);
    write_string(" actual ");
    write_hex_u64(pe_j4_result.actual_base);
    write_string(" delta ");
    write_hex_u64(pe_j4_result.delta);
    write_string(" section ");
    write_hex_u32(pe_j4_result.reloc_section_rva);
    write_string("/");
    write_hex_u32(pe_j4_result.reloc_section_bytes);
    write_string(" fixups ");
    write_hex_u32(pe_j4_result.first_fixup_rva);
    write_string("/");
    write_hex_u32(pe_j4_result.last_fixup_rva);
    write_string(" values ");
    write_hex_u64(pe_j4_rdata_before);
    write_string("/");
    write_hex_u64(pe_j4_rdata_after);
    write_string(" ");
    write_hex_u64(pe_j4_data_before);
    write_string("/");
    write_hex_u64(pe_j4_data_after);
    write_string(" prot ");
    write_hex_u32(pe_j4_rdata_prot_after);
    write_string("/");
    write_hex_u32(pe_j4_data_prot_after);
    write_string(" checksum ");
    write_hex_u32(pe_j4_result.before_checksum);
    write_string("/");
    write_hex_u32(pe_j4_result.after_checksum);
    write_string(" deny ");
    write_dec_u32(pe_j4_denied);
    write_string("/");
    write_dec_u32(pe_j4_denied_error);
    write_string(" cleanup ");
    write_dec_u32(pe_j4_cleanup);
    write_string(" positive ");
    write_dec_u32(pe_j4_positive);
    write_line("");
    write_string("[x64] pe-J5 imports ");
    write_dec_u32(pe_j5_resolve);
    write_string(" desc ");
    write_dec_u32(pe_j5_result.descriptor_count);
    write_string(" thunks ");
    write_dec_u32(pe_j5_result.thunk_count);
    write_string(" names ");
    write_dec_u32(pe_j5_result.name_import_count);
    write_string(" ordinals ");
    write_dec_u32(pe_j5_result.ordinal_import_count);
    write_string(" resolved ");
    write_dec_u32(pe_j5_result.resolved_count);
    write_string(" dir ");
    write_hex_u32(pe_j5_result.import_directory_rva);
    write_string("/");
    write_hex_u32(pe_j5_result.import_directory_bytes);
    write_string(" dll ");
    write_hex_u32(pe_j5_result.dll_name_rva);
    write_string(" iat ");
    write_hex_u32(pe_j5_result.first_thunk_rva);
    write_string("/");
    write_hex_u32(pe_j5_result.last_thunk_rva);
    write_string(" value ");
    write_hex_u64(pe_j5_iat_before);
    write_string("/");
    write_hex_u64(pe_j5_iat_after);
    write_string(" funcs ");
    write_hex_u64(pe_j5_result.first_function);
    write_string("/");
    write_hex_u64(pe_j5_result.last_function);
    write_string(" prot ");
    write_hex_u32(pe_j5_rdata_prot_after);
    write_string(" checksum ");
    write_hex_u32(pe_j5_result.dll_checksum);
    write_string("/");
    write_hex_u32(pe_j5_result.symbol_checksum);
    write_string("/");
    write_hex_u32(pe_j5_result.iat_checksum);
    write_string(" deny ");
    write_dec_u32(pe_j5_denied);
    write_string("/");
    write_dec_u32(pe_j5_denied_error);
    write_string(" cleanup ");
    write_dec_u32(pe_j5_cleanup);
    write_string(" positive ");
    write_dec_u32(pe_j5_positive);
    write_line("");
    write_string("[x64] pe-J6 tls ");
    write_dec_u32(pe_j6_handle);
    write_string(" dir ");
    write_hex_u32(pe_j6_result.tls_directory_rva);
    write_string("/");
    write_hex_u32(pe_j6_result.tls_directory_bytes);
    write_string(" raw ");
    write_hex_u64(pe_j6_result.raw_start_va);
    write_string("/");
    write_hex_u64(pe_j6_result.raw_end_va);
    write_string(" index ");
    write_hex_u64(pe_j6_result.index_va);
    write_string("/");
    write_dec_u32(pe_j6_index_slot_value);
    write_string(" callbacks ");
    write_hex_u64(pe_j6_result.callbacks_va);
    write_string(" block ");
    write_hex_u64(pe_j6_result.tls_block_base);
    write_string("/");
    write_hex_u64(pe_j6_result.tls_block_bytes);
    write_string(" bytes ");
    write_dec_u32(pe_j6_result.template_bytes);
    write_string("/");
    write_dec_u32(pe_j6_result.zero_fill_bytes);
    write_string(" first ");
    write_hex_u32(pe_j6_block_first);
    write_string(" zero ");
    write_dec_u32(pe_j6_block_zero_ok);
    write_string(" cb ");
    write_dec_u32(pe_j6_result.callback_count);
    write_string("/");
    write_dec_u32(pe_j6_result.invoked_count);
    write_string(" cbva ");
    write_hex_u64(pe_j6_result.first_callback);
    write_string("/");
    write_hex_u64(pe_j6_result.last_callback);
    write_string(" reason ");
    write_dec_u32(g_pe_j6_callback_reason);
    write_string(" order ");
    write_dec_u32(g_pe_j6_callback_order);
    write_string("/");
    write_dec_u32(pe_j6_entry_order);
    write_string("/");
    write_dec_u32(pe_j6_before_entry);
    write_string(" prot ");
    write_hex_u32(pe_j6_rdata_prot_after);
    write_string("/");
    write_hex_u32(pe_j6_data_prot_after);
    write_string(" checksum ");
    write_hex_u32(pe_j6_result.template_checksum);
    write_string("/");
    write_hex_u32(pe_j6_result.block_checksum);
    write_string("/");
    write_hex_u32(pe_j6_result.callback_checksum);
    write_string(" deny ");
    write_dec_u32(pe_j6_denied);
    write_string("/");
    write_dec_u32(pe_j6_denied_error);
    write_string(" cleanup ");
    write_dec_u32(pe_j6_cleanup);
    write_string(" positive ");
    write_dec_u32(pe_j6_positive);
    write_line("");
    write_string("[x64] pe-J7 pdata ");
    write_dec_u32(pe_j7_register);
    write_string(" dir ");
    write_hex_u32(pe_j7_result.exception_directory_rva);
    write_string("/");
    write_hex_u32(pe_j7_result.exception_directory_bytes);
    write_string(" funcs ");
    write_dec_u32(pe_j7_result.function_count);
    write_string("/");
    write_dec_u32(pe_j7_result.registered_count);
    write_string(" table ");
    write_hex_u64(pe_j7_result.table_base);
    write_string("/");
    write_hex_u64(pe_j7_result.table_bytes);
    write_string(" range ");
    write_hex_u32(pe_j7_result.first_begin_rva);
    write_string("/");
    write_hex_u32(pe_j7_result.last_end_rva);
    write_string(" unwind ");
    write_hex_u32(pe_j7_result.first_unwind_rva);
    write_string("/");
    write_hex_u32(pe_j7_result.last_unwind_rva);
    write_string(" first ");
    write_hex_u32(pe_j7_first_begin);
    write_string("/");
    write_hex_u32(pe_j7_first_end);
    write_string("/");
    write_hex_u32(pe_j7_first_unwind);
    write_string(" ctx ");
    write_dec_u32(pe_j7_result.persona_stored);
    write_string("/");
    write_dec_u32(pe_j7_context_match);
    write_string("/");
    write_dec_u32(pe_j7_type);
    write_string(" prot ");
    write_hex_u32(pe_j7_text_prot_after);
    write_string("/");
    write_hex_u32(pe_j7_rdata_prot_after);
    write_string(" checksum ");
    write_hex_u32(pe_j7_result.table_checksum);
    write_string(" deny ");
    write_dec_u32(pe_j7_denied);
    write_string("/");
    write_dec_u32(pe_j7_denied_error);
    write_string(" cleanup ");
    write_dec_u32(pe_j7_cleanup);
    write_string("/");
    write_dec_u32(pe_j7_after_cleanup);
    write_string(" positive ");
    write_dec_u32(pe_j7_positive);
    write_line("");
    write_string("[x64] pe-J8 teb ");
    write_dec_u32(pe_j8_setup);
    write_string(" base ");
    write_hex_u64(pe_j8_result.teb_base);
    write_string(" peb ");
    write_hex_u64(pe_j8_result.peb_base);
    write_string(" stack ");
    write_hex_u64(pe_j8_result.stack_base_value);
    write_string("/");
    write_hex_u64(pe_j8_result.stack_limit_value);
    write_string(" self ");
    write_hex_u64(pe_j8_result.self_value);
    write_string(" gs ");
    write_hex_u64(pe_j8_result.gs_base_before);
    write_string("/");
    write_hex_u64(pe_j8_result.gs_base_after);
    write_string("/");
    write_hex_u64(pe_j8_gs_self);
    write_string("/");
    write_hex_u64(pe_j8_gs_restore);
    write_string(" fields ");
    write_hex_u64(pe_j8_result.exception_list_value);
    write_string("/");
    write_hex_u64(pe_j8_result.tls_pointer_value);
    write_string("/");
    write_hex_u64(pe_j8_result.peb_value);
    write_string(" ctx ");
    write_dec_u32(pe_j8_result.context_stored);
    write_string("/");
    write_dec_u32(pe_j8_context_match);
    write_string("/");
    write_dec_u32(pe_j8_type);
    write_string(" pte ");
    write_dec_u32(pe_j8_present);
    write_string("/");
    write_hex_u32(pe_j8_prot);
    write_string(" checksum ");
    write_hex_u32(pe_j8_result.page_checksum);
    write_string(" deny ");
    write_dec_u32(pe_j8_denied);
    write_string("/");
    write_dec_u32(pe_j8_denied_error);
    write_string(" cleanup ");
    write_dec_u32(pe_j8_cleanup);
    write_string("/");
    write_dec_u32(pe_j8_after_cleanup);
    write_string(" positive ");
    write_dec_u32(pe_j8_positive);
    write_line("");
    write_string("[x64] pe-J9 peb ");
    write_dec_u32(pe_j9_setup_peb);
    write_string(" image ");
    write_hex_u64(pe_j9_result.image_base_value);
    write_string("/");
    write_hex_u64(pe_j9_map_result.actual_base);
    write_string(" peb ");
    write_hex_u64(pe_j9_result.peb_base);
    write_string(" gs ");
    write_hex_u64(pe_j9_gs_peb);
    write_string("/");
    write_hex_u64(pe_j9_gs_image);
    write_string(" params ");
    write_hex_u64(pe_j9_result.process_parameters_value);
    write_string("/");
    write_hex_u64(pe_j9_result.process_parameters);
    write_string(" os ");
    write_dec_u32(pe_j9_result.os_major_value);
    write_string("/");
    write_dec_u32(pe_j9_result.os_minor_value);
    write_string("/");
    write_dec_u32(pe_j9_result.os_build_value);
    write_string(" nt ");
    write_hex_u32(pe_j9_result.nt_global_flag_value);
    write_string(" strings ");
    write_dec_u32(pe_j9_result.image_path_bytes);
    write_string("/");
    write_dec_u32(pe_j9_result.command_line_bytes);
    write_string("/");
    write_dec_u32(pe_j9_result.environment_bytes);
    write_string(" checksums ");
    write_hex_u32(pe_j9_result.image_path_checksum);
    write_string("/");
    write_hex_u32(pe_j9_result.command_line_checksum);
    write_string("/");
    write_hex_u32(pe_j9_result.environment_checksum);
    write_string(" ctx ");
    write_dec_u32(pe_j9_result.context_stored);
    write_string("/");
    write_dec_u32(pe_j9_context_match);
    write_string("/");
    write_dec_u32(pe_j9_type);
    write_string(" map ");
    write_dec_u32(pe_j9_map_result.mapped_count);
    write_string(" deny ");
    write_dec_u32(pe_j9_denied);
    write_string("/");
    write_dec_u32(pe_j9_denied_error);
    write_string(" cleanup ");
    write_dec_u32(pe_j9_cleanup);
    write_string("/");
    write_dec_u32(pe_j9_after_cleanup);
    write_string(" positive ");
    write_dec_u32(pe_j9_positive);
    write_line("");
    write_string("[x64] pe-J10 kuser ");
    write_dec_u32(pe_j10_setup);
    write_string(" base ");
    write_hex_u64(pe_j10_result.base);
    write_string(" bytes ");
    write_dec_u32((u32)pe_j10_result.page_bytes);
    write_string(" time ");
    write_hex_u32(pe_j10_system_low_before);
    write_string("/");
    write_hex_u32(pe_j10_system_low_after);
    write_string(" ticks ");
    write_dec_u32(pe_j10_tick_before);
    write_string("/");
    write_dec_u32(pe_j10_tick_after);
    write_string(" product ");
    write_dec_u32(pe_j10_product);
    write_string(" prot ");
    write_dec_u32(pe_j10_present);
    write_string("/");
    write_hex_u32(pe_j10_prot);
    write_string(" root ");
    write_dec_u32(pe_j10_result.system_root_bytes);
    write_string(" checksums ");
    write_hex_u32(pe_j10_result.processor_feature_checksum);
    write_string("/");
    write_hex_u32(pe_j10_result.page_checksum);
    write_string("/");
    write_hex_u32(pe_j10_checksum_after_tick);
    write_string(" ctx ");
    write_dec_u32(pe_j10_result.context_stored);
    write_string("/");
    write_dec_u32(pe_j10_context_match);
    write_string("/");
    write_dec_u32(pe_j10_updates_after_tick);
    write_string(" high ");
    write_dec_u32(pe_j10_high_match);
    write_string(" advance ");
    write_dec_u32(pe_j10_tick_advanced);
    write_string(" deny ");
    write_dec_u32(pe_j10_denied);
    write_string("/");
    write_dec_u32(pe_j10_denied_error);
    write_string(" cleanup ");
    write_dec_u32(pe_j10_cleanup);
    write_string("/");
    write_dec_u32(pe_j10_after_cleanup);
    write_string(" positive ");
    write_dec_u32(pe_j10_positive);
    write_line("");
    write_string("[x64] pe-J11 cookie ");
    write_dec_u32(pe_j11_init_cookie);
    write_string(" dir ");
    write_hex_u32(pe_j11_result.load_config_directory_rva);
    write_string("/");
    write_hex_u32(pe_j11_result.load_config_directory_bytes);
    write_string(" field ");
    write_hex_u64(pe_j11_result.security_cookie_field);
    write_string("/");
    write_hex_u64(pe_j11_result.security_cookie_address);
    write_string(" before ");
    write_hex_u64(pe_j11_result.cookie_before);
    write_string(" after ");
    write_hex_u64(pe_j11_result.cookie_after);
    write_string(" second ");
    write_hex_u64(pe_j11_second_result.cookie_after);
    write_string(" checksums ");
    write_hex_u32(pe_j11_result.cookie_checksum);
    write_string("/");
    write_hex_u32(pe_j11_second_result.cookie_checksum);
    write_string(" prot ");
    write_hex_u32(pe_j11_result.page_protection);
    write_string(" ctx ");
    write_dec_u32(pe_j11_result.context_stored);
    write_string("/");
    write_dec_u32(pe_j11_context_match);
    write_string("/");
    write_dec_u32(pe_j11_type);
    write_string(" unique ");
    write_dec_u32(pe_j11_unique);
    write_string(" deny ");
    write_dec_u32(pe_j11_denied);
    write_string("/");
    write_dec_u32(pe_j11_denied_error);
    write_string(" cleanup ");
    write_dec_u32(pe_j11_cleanup);
    write_string("/");
    write_dec_u32(pe_j11_after_cleanup);
    write_string(" second-cleanup ");
    write_dec_u32(pe_j11_second_cleanup);
    write_string("/");
    write_dec_u32(pe_j11_second_after_cleanup);
    write_string(" positive ");
    write_dec_u32(pe_j11_positive);
    write_line("");
    write_string("[x64] pe-J12 entry ");
    write_dec_u32(pe_j12_launch);
    write_string(" rip ");
    write_hex_u64(pe_j12_result.entry_rip);
    write_string("/");
    write_hex_u64(pe_j12_result.transfer_rip);
    write_string(" rsp ");
    write_hex_u64(pe_j12_result.initial_rsp);
    write_string(" stack ");
    write_hex_u64(pe_j12_result.stack_base);
    write_string("/");
    write_hex_u64(pe_j12_result.stack_top);
    write_string(" args ");
    write_hex_u64(pe_j12_result.arg_rcx);
    write_string("/");
    write_hex_u64(pe_j12_result.arg_rdx);
    write_string("/");
    write_hex_u64(pe_j12_result.arg_r8);
    write_string(" pages ");
    write_dec_u32(pe_j12_result.entry_page_present);
    write_string("/");
    write_hex_u32(pe_j12_result.entry_page_prot);
    write_string("/");
    write_dec_u32(pe_j12_result.stack_page_present);
    write_string("/");
    write_hex_u32(pe_j12_result.stack_page_prot);
    write_string(" transfer ");
    write_dec_u32(pe_j12_result.transfer_ready);
    write_string("/");
    write_dec_u32(pe_j12_result.transfer_executed);
    write_string("/");
    write_hex_u32(pe_j12_result.transfer_result);
    write_string("/");
    write_hex_u32(pe_j12_result.transfer_aux);
    write_string(" selectors ");
    write_hex_u32(pe_j12_result.transfer_selectors);
    write_string(" rflags ");
    write_hex_u32(pe_j12_result.transfer_rflags);
    write_string(" ctx ");
    write_dec_u32(pe_j12_result.context_stored);
    write_string("/");
    write_dec_u32(pe_j12_context_match);
    write_string("/");
    write_dec_u32(pe_j12_type);
    write_string(" deny ");
    write_dec_u32(pe_j12_denied);
    write_string("/");
    write_dec_u32(pe_j12_denied_error);
    write_string(" ntdll ");
    write_dec_u32(pe_j12_ntdll_load);
    write_string("/");
    write_hex_u64(pe_j12_ntdll_result.ldr_initialize_thunk);
    write_string(" pte ");
    write_dec_u32(pe_j12_ntdll_text_pte_before_exe);
    write_string("/");
    write_hex_u32(pe_j12_ntdll_text_prot_before_exe);
    write_string("/");
    write_dec_u32(pe_j12_ntdll_text_pte_after_exe);
    write_string("/");
    write_hex_u32(pe_j12_ntdll_text_prot_after_exe);
    write_string(" exe ");
    write_dec_u32(pe_j12_exe_launch);
    write_string(" rip ");
    write_hex_u64(pe_j12_exe_result.entry_rip);
    write_string("/");
    write_hex_u64(pe_j12_exe_result.transfer_rip);
    write_string(" args ");
    write_hex_u64(pe_j12_exe_result.arg_rcx);
    write_string("/");
    write_hex_u64(pe_j12_exe_result.arg_rdx);
    write_string("/");
    write_hex_u64(pe_j12_exe_result.arg_r8);
    write_string(" ready ");
    write_dec_u32(pe_j12_exe_result.transfer_ready);
    write_string("/");
    write_dec_u32(pe_j12_exe_result.transfer_executed);
    write_string(" pages ");
    write_dec_u32(pe_j12_exe_result.entry_page_present);
    write_string("/");
    write_hex_u32(pe_j12_exe_result.entry_page_prot);
    write_string("/");
    write_dec_u32(pe_j12_exe_result.stack_page_present);
    write_string("/");
    write_hex_u32(pe_j12_exe_result.stack_page_prot);
    write_string(" result ");
    write_hex_u32(pe_j12_exe_result.transfer_result);
    write_string("/");
    write_hex_u32(pe_j12_exe_result.transfer_aux);
    write_string(" ctx ");
    write_dec_u32(pe_j12_exe_result.context_stored);
    write_string("/");
    write_dec_u32(pe_j12_exe_context_match);
    write_string(" err ");
    write_dec_u32(pe_j12_exe_result.error);
    write_string(" cleanup ");
    write_dec_u32(pe_j12_cleanup);
    write_string("/");
    write_dec_u32(pe_j12_after_cleanup);
    write_string(" positive ");
    write_dec_u32(pe_j12_positive);
    write_line("");
#endif
#endif /* LIMITLESS_SCAFFOLD_ELF_PE_PE_OUTPUT */

#if defined(LIMITLESS_SCAFFOLD_ELF_PE_ELF_OUTPUT)
#if defined(LIMITLESS_X64_UEFI_KERNEL) && LIMITLESS_X64_UEFI_KERNEL
    write_string("[x64] elf-E1 parse ");
    write_dec_u32(elf_e1_parse);
    write_string(" type ");
    write_dec_u32((u32)elf_e1_header.type);
    write_string(" machine ");
    write_dec_u32((u32)elf_e1_header.machine);
    write_string(" entry ");
    write_hex_u64(elf_e1_header.entry);
    write_string(" phoff ");
    write_hex_u64(elf_e1_header.phoff);
    write_string(" phnum ");
    write_dec_u32((u32)elf_e1_header.phnum);
    write_string(" phent ");
    write_dec_u32((u32)elf_e1_header.phentsize);
    write_string(" bad-magic ");
    write_dec_u32(elf_e1_bad_magic);
    write_string(" err ");
    write_dec_u32(elf_e1_bad_magic_error);
    write_string(" bad-machine ");
    write_dec_u32(elf_e1_bad_machine);
    write_string(" err ");
    write_dec_u32(elf_e1_bad_machine_error);
    write_string(" positive ");
    write_dec_u32(elf_e1_positive);
    write_line("");
    write_string("[x64] elf-E2 phdrs ");
    write_dec_u32(elf_e2_parse);
    write_string(" loads ");
    write_dec_u32(elf_e2_summary.load_count);
    write_string(" stack ");
    write_dec_u32(elf_e2_summary.gnu_stack_count);
    write_string(" exec-loads ");
    write_dec_u32(elf_e2_summary.executable_loads);
    write_string(" write-loads ");
    write_dec_u32(elf_e2_summary.writable_loads);
    write_string(" mem ");
    write_hex_u64(elf_e2_summary.load_mem_bytes);
    write_string(" first ");
    write_hex_u64(elf_e2_summary.first_load_vaddr);
    write_string(" max ");
    write_hex_u64(elf_e2_summary.max_load_end);
    write_string(" truncated ");
    write_dec_u32(elf_e2_truncated);
    write_string(" err ");
    write_dec_u32(elf_e2_truncated_error);
    write_string(" bad-align ");
    write_dec_u32(elf_e2_bad_align_parse);
    write_string(" err ");
    write_dec_u32(elf_e2_bad_align_error);
    write_string(" positive ");
    write_dec_u32(elf_e2_positive);
    write_line("");
    write_string("[x64] elf-E3 map ");
    write_dec_u32(elf_e3_map);
    write_string(" segments ");
    write_dec_u32(elf_e3_result.mapped_count);
    write_string(" bytes ");
    write_hex_u64(elf_e3_result.total_map_bytes);
    write_string(" file ");
    write_hex_u64(elf_e3_result.total_file_bytes);
    write_string(" bss ");
    write_hex_u64(elf_e3_result.total_bss_bytes);
    write_string(" text-pte ");
    write_dec_u32(elf_e3_text_pte);
    write_string(" text-prot ");
    write_hex_u32(elf_e3_text_prot);
    write_string(" data-pte ");
    write_dec_u32(elf_e3_data_pte);
    write_string(" data-prot ");
    write_hex_u32(elf_e3_data_prot);
    write_string(" bss-zero ");
    write_dec_u32(elf_e3_bss_zero);
    write_string(" source ");
    write_hex_u32(elf_e3_result.source_checksum);
    write_string(" mapped ");
    write_hex_u32(elf_e3_result.mapped_checksum);
    write_string(" denied ");
    write_dec_u32(elf_e3_denied);
    write_string(" err ");
    write_dec_u32(elf_e3_denied_error);
    write_string(" cleanup ");
    write_dec_u32(elf_e3_cleanup);
    write_string(" positive ");
    write_dec_u32(elf_e3_positive);
    write_line("");
    write_string("[x64] elf-E4 relro ");
    write_dec_u32(elf_e4_apply);
    write_string(" count ");
    write_dec_u32(elf_e4_result.relro_count);
    write_string(" protected ");
    write_dec_u32(elf_e4_result.protected_count);
    write_string(" bytes ");
    write_hex_u64(elf_e4_result.total_protected_bytes);
    write_string(" first ");
    write_hex_u64(elf_e4_result.first_protected_vaddr);
    write_string(" max ");
    write_hex_u64(elf_e4_result.max_protected_end);
    write_string(" text-prot ");
    write_hex_u32(elf_e4_text_prot);
    write_string(" data-prot ");
    write_hex_u32(elf_e4_data_prot);
    write_string(" denied ");
    write_dec_u32(elf_e4_denied);
    write_string(" err ");
    write_dec_u32(elf_e4_denied_error);
    write_string(" cleanup ");
    write_dec_u32(elf_e4_cleanup);
    write_string(" positive ");
    write_dec_u32(elf_e4_positive);
    write_line("");
    write_string("[x64] elf-E5 auxv ");
    write_dec_u32(elf_e5_build);
    write_string(" entries ");
    write_dec_u32(elf_e5_auxv.entry_count);
    write_string(" required ");
    write_dec_u32(elf_e5_required);
    write_string(" phdr ");
    write_hex_u64(elf64_auxv_value(&elf_e5_auxv, ELF64_AT_PHDR));
    write_string(" phnum ");
    write_dec_u32((u32)elf64_auxv_value(&elf_e5_auxv, ELF64_AT_PHNUM));
    write_string(" entry ");
    write_hex_u64(elf64_auxv_value(&elf_e5_auxv, ELF64_AT_ENTRY));
    write_string(" base ");
    write_hex_u64(elf64_auxv_value(&elf_e5_auxv, ELF64_AT_BASE));
    write_string(" pagesz ");
    write_dec_u32((u32)elf64_auxv_value(&elf_e5_auxv, ELF64_AT_PAGESZ));
    write_string(" random-bytes ");
    write_dec_u32(elf_e5_auxv.random_byte_count);
    write_string(" random ");
    write_hex_u32(elf_e5_auxv.random_checksum);
    write_string(" platform ");
    write_string((const char *)&elf_e5_auxv.platform[0]);
    write_string(" platform-sum ");
    write_hex_u32(elf_e5_auxv.platform_checksum);
    write_string(" null ");
    write_dec_u32(elf_e5_null_term);
    write_string(" denied ");
    write_dec_u32(elf_e5_denied);
    write_string(" err ");
    write_dec_u32(elf_e5_denied_error);
    write_string(" positive ");
    write_dec_u32(elf_e5_positive);
    write_line("");
    write_string("[x64] elf-E6 stack build ");
    write_dec_u32(elf_e6_build);
    write_string(" map ");
    write_dec_u32(elf_e6_map);
    write_string(" rsp ");
    write_hex_u64(elf_e6_stack_result.initial_rsp);
    write_string(" align ");
    write_dec_u32(elf_e6_stack_result.alignment_ok);
    write_string(" argc ");
    write_dec_u32(elf_e6_argc_match);
    write_string(" argv0 ");
    write_dec_u32(elf_e6_argv0_match);
    write_string(" env0 ");
    write_dec_u32(elf_e6_env0_match);
    write_string(" auxv ");
    write_hex_u64(elf_e6_stack_result.auxv_address);
    write_string(" slots ");
    write_dec_u32(elf_e6_stack_result.pointer_slot_count);
    write_string(" strings ");
    write_dec_u32(elf_e6_stack_result.string_bytes);
    write_string(" random ");
    write_dec_u32(elf_e6_random_match);
    write_string(" platform ");
    write_dec_u32(elf_e6_platform_match);
    write_string(" rewrite ");
    write_dec_u32(elf_e6_auxv_rewrite);
    write_string(" nulls ");
    write_dec_u32(elf_e6_stack_result.argv_null_ok);
    write_string("/");
    write_dec_u32(elf_e6_stack_result.envp_null_ok);
    write_string("/");
    write_dec_u32(elf_e6_stack_result.auxv_null_ok);
    write_string(" denied ");
    write_dec_u32(elf_e6_denied);
    write_string(" err ");
    write_dec_u32(elf_e6_denied_error);
    write_string(" cleanup ");
    write_dec_u32(elf_e6_cleanup);
    write_string(" positive ");
    write_dec_u32(elf_e6_positive);
    write_line("");
    write_string("[x64] elf-E7 static-launch load ");
    write_dec_u32(elf_e7_launch);
    write_string(" mapped ");
    write_dec_u32(elf_e7_result.load_result.mapped_count);
    write_string(" vmas ");
    write_dec_u32(elf_e7_vma_count);
    write_string(" entry ");
    write_hex_u64(elf_e7_result.entry_rip);
    write_string(" rsp ");
    write_hex_u64(elf_e7_result.initial_rsp);
    write_string(" phdr ");
    write_hex_u64(elf_e7_result.phdr_vaddr);
    write_string(" stack ");
    write_hex_u64(elf_e7_result.stack_base);
    write_string(" transfer-ready ");
    write_dec_u32(elf_e7_transfer_ready);
    write_string(" transfer-exec ");
    write_dec_u32(elf_e7_result.transfer_executed);
    write_string(" entry-prot ");
    write_hex_u32(elf_e7_result.entry_page_prot);
    write_string(" stack-prot ");
    write_hex_u32(elf_e7_result.stack_page_prot);
    write_string(" abi-write ");
    write_hex_u64(elf_e7_write_return);
    write_string(" audit ");
    write_dec_u32(elf_e7_write_match);
    write_string(" abi-exit ");
    write_hex_u64(elf_e7_exit_return);
    write_string(" code ");
    write_dec_u32(elf_e7_exit_code);
    write_string(" release ");
    write_dec_u32(elf_e7_vma_released);
    write_string("/");
    write_dec_u32(elf_e7_fd_released);
    write_string("/");
    write_dec_u32(elf_e7_persona_released);
    write_string("/");
    write_dec_u32(elf_e7_audit_released);
    write_string(" slots ");
    write_dec_u32(elf_e7_slots_clear);
    write_string(" pages ");
    write_dec_u32(elf_e7_pages_clear);
    write_string(" deny ");
    write_dec_u32(elf_e7_deny);
    write_string(" err ");
    write_dec_u32(elf_e7_deny_error);
    write_string(" positive ");
    write_dec_u32(elf_e7_positive);
    write_line("");
    write_string("[x64] fd-B2 release cleanup ");
    write_dec_u32(fd_cleanup);
    write_string(" post ");
    write_dec_u32(fd_post_detach);
    write_line("");
    input64_init();
    console64_init();
    fs64_init();
    capability64_init();
#endif
#endif /* LIMITLESS_SCAFFOLD_ELF_PE_ELF_OUTPUT */

#if !defined(LIMITLESS_SCAFFOLD_UNITY)
void limitless_scaffold_elf_pe_anchor(void) {}
#endif
