/* LimitlessOS scaffold unity wrapper. Domain fragments live in scaffold_*.c. */
#define LIMITLESS_SCAFFOLD_UNITY 1

#define LIMITLESS_SCAFFOLD_CORE_TOP 1
#include "scaffold_core.c"
#undef LIMITLESS_SCAFFOLD_CORE_TOP

#define LIMITLESS_SCAFFOLD_VMA_FD_PIPE_BOOTSTRAP 1
#include "scaffold_vma_fd_pipe.c"
#undef LIMITLESS_SCAFFOLD_VMA_FD_PIPE_BOOTSTRAP

#define LIMITLESS_SCAFFOLD_CORE_PROCESS_EXECUTION 1
#include "scaffold_core.c"
#undef LIMITLESS_SCAFFOLD_CORE_PROCESS_EXECUTION

#define LIMITLESS_SCAFFOLD_VMA_FD_PIPE_FD_OUTPUT 1
#include "scaffold_vma_fd_pipe.c"
#undef LIMITLESS_SCAFFOLD_VMA_FD_PIPE_FD_OUTPUT

#define LIMITLESS_SCAFFOLD_LINUX_ABI_OUTPUT 1
#include "scaffold_linux.c"
#undef LIMITLESS_SCAFFOLD_LINUX_ABI_OUTPUT

#define LIMITLESS_SCAFFOLD_WINDOWS_SEH_OUTPUT 1
#include "scaffold_windows.c"
#undef LIMITLESS_SCAFFOLD_WINDOWS_SEH_OUTPUT

#define LIMITLESS_SCAFFOLD_ELF_PE_PE_OUTPUT 1
#include "scaffold_elf_pe.c"
#undef LIMITLESS_SCAFFOLD_ELF_PE_PE_OUTPUT

#define LIMITLESS_SCAFFOLD_WINDOWS_KL_OUTPUT 1
#include "scaffold_windows.c"
#undef LIMITLESS_SCAFFOLD_WINDOWS_KL_OUTPUT

#define LIMITLESS_SCAFFOLD_MACOS_OUTPUT 1
#include "scaffold_macos.c"
#undef LIMITLESS_SCAFFOLD_MACOS_OUTPUT

#define LIMITLESS_SCAFFOLD_LINUX_PERSONA_PQ_OUTPUT 1
#include "scaffold_linux.c"
#undef LIMITLESS_SCAFFOLD_LINUX_PERSONA_PQ_OUTPUT

#define LIMITLESS_SCAFFOLD_VMA_FD_PIPE_PIPE_OUTPUT 1
#include "scaffold_vma_fd_pipe.c"
#undef LIMITLESS_SCAFFOLD_VMA_FD_PIPE_PIPE_OUTPUT

#define LIMITLESS_SCAFFOLD_ELF_PE_ELF_OUTPUT 1
#include "scaffold_elf_pe.c"
#undef LIMITLESS_SCAFFOLD_ELF_PE_ELF_OUTPUT

#define LIMITLESS_SCAFFOLD_CORE_PROCESS_TAIL 1
#include "scaffold_core.c"
#undef LIMITLESS_SCAFFOLD_CORE_PROCESS_TAIL

#define LIMITLESS_SCAFFOLD_SCHED_LAUNCH_AND_TASKS 1
#include "scaffold_sched.c"
#undef LIMITLESS_SCAFFOLD_SCHED_LAUNCH_AND_TASKS

#define LIMITLESS_SCAFFOLD_STORAGE_USER_FS_LOAD 1
#include "scaffold_storage.c"
#undef LIMITLESS_SCAFFOLD_STORAGE_USER_FS_LOAD

#define LIMITLESS_SCAFFOLD_PLATFORM_SERVICES_INPUT_GUI 1
#include "scaffold_platform.c"
#undef LIMITLESS_SCAFFOLD_PLATFORM_SERVICES_INPUT_GUI

#define LIMITLESS_SCAFFOLD_STORAGE_PCI_AHCI_DRS 1
#include "scaffold_storage.c"
#undef LIMITLESS_SCAFFOLD_STORAGE_PCI_AHCI_DRS

#define LIMITLESS_SCAFFOLD_PLATFORM_USB_XHCI 1
#include "scaffold_platform.c"
#undef LIMITLESS_SCAFFOLD_PLATFORM_USB_XHCI

#define LIMITLESS_SCAFFOLD_NETWORK_DRS_AND_N1 1
#include "scaffold_network.c"
#undef LIMITLESS_SCAFFOLD_NETWORK_DRS_AND_N1

#define LIMITLESS_SCAFFOLD_STORAGE_NVME_FS 1
#include "scaffold_storage.c"
#undef LIMITLESS_SCAFFOLD_STORAGE_NVME_FS

#define LIMITLESS_SCAFFOLD_CORE_NATIVE_AND_ENTRY 1
#include "scaffold_core.c"
#undef LIMITLESS_SCAFFOLD_CORE_NATIVE_AND_ENTRY
