/* Split scaffold fragment. Real code is unity-included by scaffold.c; direct compilation emits only the anchor below. */

#if defined(LIMITLESS_SCAFFOLD_MACOS_OUTPUT)
#if defined(LIMITLESS_X64_UEFI_KERNEL) && LIMITLESS_X64_UEFI_KERNEL
    write_string("[x64] macos-abi-N1 table ");
    write_dec_u32(macos_n1_table_size);
    write_string("/");
    write_dec_u32(macos_n1_unimplemented_entries);
    write_string(" entries ");
    write_dec_u32(macos_n1_entries_installed);
    write_string(" ctx ");
    write_dec_u32(macos_n1_context_bound);
    write_string(" setup ");
    write_dec_u32(macos_n1_pid);
    write_string("/");
    write_dec_u32(macos_n1_vma_init);
    write_string("/");
    write_dec_u32(macos_n1_audit_attach);
    write_string("/");
    write_dec_u32(macos_n1_fd_init);
    write_string("/");
    write_dec_u32(macos_n1_bind);
    write_string("/");
    write_dec_u32((macos_n1_buffer_map == macos_n1_buffer_base) ? 1u : 0u);
    write_string(" getpid ");
    write_hex_u64(macos_n1_getpid_ret);
    write_string(" write ");
    write_hex_u64(macos_n1_write_ret);
    write_string(" console ");
    write_dec_u32(macos_n1_console_after_count - macos_n1_console_before_count);
    write_string("/");
    write_dec_u32(macos_n1_console_after_bytes - macos_n1_console_before_bytes);
    write_string(" open ");
    write_hex_u64(macos_n1_open_ret);
    write_string(" read ");
    write_hex_u64(macos_n1_read_ret);
    write_string("/");
    write_hex_u32(macos_n1_read_checksum);
    write_string(" stat ");
    write_hex_u64(macos_n1_stat_ret);
    write_string("/");
    write_hex_u64(macos_n1_stat_size);
    write_string("/");
    write_hex_u32(macos_n1_stat_mode);
    write_string(" fstat ");
    write_hex_u64(macos_n1_fstat_ret);
    write_string(" close ");
    write_hex_u64(macos_n1_close_ret);
    write_string("/");
    write_dec_u32(
        (macos_n1_open_ret < (u64)FD64_TABLE_LIMIT)
            ? ((fd64_entry_type(macos_n1_pid, (u32)macos_n1_open_ret) == FD64_TYPE_EMPTY)
                ? 1u
                : 0u)
            : 0u);
    write_string(" mmap ");
    write_hex_u64(macos_n1_mmap_ret);
    write_string(" pte ");
    write_dec_u32(macos_n1_pte_mapped);
    write_string("/");
    write_hex_u32(macos_n1_prot_after_map);
    write_string(" protect ");
    write_hex_u64(macos_n1_mprotect_ret);
    write_string("/");
    write_hex_u32(macos_n1_prot_after_protect);
    write_string(" munmap ");
    write_hex_u64(macos_n1_munmap_ret);
    write_string("/");
    write_dec_u32(macos_n1_pte_after_unmap);
    write_string(" clock ");
    write_hex_u64(macos_n1_clock_ret);
    write_string("/");
    write_hex_u64(macos_n1_time_sec);
    write_string("/");
    write_hex_u64(macos_n1_time_nsec);
    write_string(" sysctl ");
    write_hex_u64(macos_n1_sysctl_ret);
    write_string("/");
    write_dec_u32((u32)macos_n1_sysctl_len);
    write_string("/");
    write_dec_u32(macos_n1_sysctl_prefix);
    write_string("/");
    write_dec_u32(macos_abi64_last_sysctl_name0());
    write_string("/");
    write_dec_u32(macos_abi64_last_sysctl_name1());
    write_string("/");
    write_dec_u32(macos_abi64_last_sysctl_bytes());
    write_string(" deny ");
    write_hex_u64(macos_n1_bad_open_ret);
    write_string(" unimpl ");
    write_hex_u64(macos_n1_unimpl_ret);
    write_string(" audit ");
    write_dec_u32(macos_n1_audit_before);
    write_string("/");
    write_dec_u32(macos_n1_audit_after_unimpl);
    write_string("/");
    write_dec_u32(macos_n1_read_unimpl_record);
    write_string("/");
    write_dec_u32((u32)macos_n1_unimpl_record.event_type);
    write_string("/");
    write_dec_u32((u32)macos_n1_unimpl_record.event_code);
    write_string("/");
    write_dec_u32(macos_n1_unimpl_record.result);
    write_string("/");
    write_dec_u32((u32)macos_n1_unimpl_record.persona_type);
    write_string(" exit ");
    write_hex_u64(macos_n1_exit_ret);
    write_string("/");
    write_dec_u32(macos_abi64_last_exit_vma_regions());
    write_string("/");
    write_dec_u32(macos_abi64_last_exit_fd_entries());
    write_string("/");
    write_dec_u32(macos_abi64_last_exit_persona_released());
    write_string("/");
    write_dec_u32(macos_abi64_last_exit_audit_released());
    write_string(" cleanup ");
    write_dec_u32(macos_n1_clone_release);
    write_string("/");
    write_dec_u32(macos_n1_after_cleanup);
    write_string(" positive ");
    write_dec_u32(macos_n1_positive);
    write_line("");
    write_string("[x64] macos-mach-N2 table ");
    write_dec_u32(macos_n2_table_size);
    write_string("/");
    write_dec_u32(macos_n2_unimplemented_entries);
    write_string(" entries ");
    write_dec_u32(macos_n2_entries_installed);
    write_string(" setup ");
    write_dec_u32(macos_n2_pid);
    write_string("/");
    write_dec_u32(macos_n2_vma_init);
    write_string("/");
    write_dec_u32(macos_n2_audit_attach);
    write_string("/");
    write_dec_u32(macos_n2_bind);
    write_string("/");
    write_dec_u32((macos_n2_buffer_map == macos_n2_buffer_base) ? 1u : 0u);
    write_string(" ports ");
    write_hex_u64(macos_n2_task_port);
    write_string("/");
    write_hex_u64(macos_n2_thread_port);
    write_string("/");
    write_hex_u64(macos_n2_host_port);
    write_string("/");
    write_hex_u64(macos_n2_reply_port);
    write_string(" live ");
    write_dec_u32(macos_n2_live_after_ports);
    write_string("/");
    write_dec_u32(macos_mach64_total_live_port_count());
    write_string(" kinds ");
    write_dec_u32(macos_n2_task_kind);
    write_string("/");
    write_dec_u32(macos_n2_thread_kind);
    write_string("/");
    write_dec_u32(macos_n2_host_kind);
    write_string(" reply-rights ");
    write_hex_u32(macos_n2_reply_rights);
    write_string(" backing ");
    write_dec_u32(macos_n2_task_endpoint);
    write_string("/");
    write_dec_u32(macos_n2_reply_endpoint);
    write_string("/");
    write_hex_u32(macos_n2_reply_capability);
    write_string(" msg ");
    write_hex_u64(macos_n2_send_ret);
    write_string("/");
    write_hex_u64(macos_n2_recv_ret);
    write_string(" pending ");
    write_dec_u32(macos_n2_pending_after_send);
    write_string("/");
    write_dec_u32(macos_n2_pending_after_recv);
    write_string(" recv ");
    write_hex_u32(macos_n2_recv_id);
    write_string("/");
    write_dec_u32(macos_n2_recv_size);
    write_string("/");
    write_hex_u32(macos_n2_recv_local);
    write_string("/");
    write_hex_u32(macos_n2_recv_remote);
    write_string("/");
    write_hex_u32(macos_n2_body_checksum);
    write_string(" counts ");
    write_dec_u32(macos_n2_send_count_after - macos_n2_send_count_before);
    write_string("/");
    write_dec_u32(macos_n2_recv_count_after - macos_n2_recv_count_before);
    write_string("/");
    write_dec_u32(macos_n2_denial_after - macos_n2_denial_before);
    write_string(" deny ");
    write_hex_u64(macos_n2_bad_send_ret);
    write_string(" unimpl ");
    write_hex_u64(macos_n2_unimpl_ret);
    write_string(" audit ");
    write_dec_u32(macos_n2_audit_before);
    write_string("/");
    write_dec_u32(macos_n2_audit_after_unimpl);
    write_string("/");
    write_dec_u32(macos_n2_read_unimpl_record);
    write_string("/");
    write_dec_u32((u32)macos_n2_unimpl_record.event_type);
    write_string("/");
    write_dec_u32((u32)macos_n2_unimpl_record.event_code);
    write_string("/");
    write_dec_u32(macos_n2_unimpl_record.result);
    write_string("/");
    write_dec_u32((u32)macos_n2_unimpl_record.persona_type);
    write_string(" last ");
    write_dec_u32(macos_mach64_last_trap());
    write_string("/");
    write_hex_u32(macos_mach64_last_result());
    write_string("/");
    write_dec_u32(macos_mach64_mach_msg_count());
    write_string("/");
    write_dec_u32(macos_mach64_unimplemented_count());
    write_string(" cleanup ");
    write_dec_u32(macos_n2_release_ports);
    write_string("/");
    write_dec_u32(macos_n2_unmap_buffer);
    write_string("/");
    write_dec_u32(macos_n2_persona_release);
    write_string("/");
    write_dec_u32(macos_n2_audit_release);
    write_string("/");
    write_dec_u32(macos_n2_clone_release);
    write_string("/");
    write_dec_u32(macos_n2_after_cleanup);
    write_string(" positive ");
    write_dec_u32(macos_n2_positive);
    write_line("");
    write_string("[x64] macos-shim-N3 load ");
    write_dec_u32(macos_n3_load);
    write_string("/");
    write_dec_u32(macos_n3_bad_load);
    write_string(" err ");
    write_dec_u32(macos_n3_load_result.error);
    write_string("/");
    write_dec_u32(macos_n3_bad_load_result.error);
    write_string(" syms ");
    write_dec_u32(macos_n3_symbol_count);
    write_string("/");
    write_dec_u32(macos_n3_resolved_count);
    write_string(" addrs ");
    write_hex_u64(macos_n3_write_addr);
    write_string("/");
    write_hex_u64(macos_n3_printf_addr);
    write_string("/");
    write_hex_u64(macos_n3_missing_addr);
    write_string(" map ");
    write_dec_u32(macos_n3_load_result.mapped_count);
    write_string("/");
    write_dec_u32(macos_n3_text_present);
    write_string("/");
    write_dec_u32(macos_n3_rodata_present);
    write_string(" prot ");
    write_hex_u32(macos_n3_load_result.text_protection);
    write_string("/");
    write_hex_u32(macos_n3_load_result.rodata_protection);
    write_string(" checks ");
    write_hex_u32(macos_n3_load_result.text_checksum);
    write_string("/");
    write_hex_u32(macos_n3_load_result.rodata_checksum);
    write_string("/");
    write_hex_u32(macos_n3_load_result.name_checksum);
    write_string(" printf ");
    write_dec_u32((u32)macos_n3_printf_result.value);
    write_string("/");
    write_dec_u32(macos_n3_console_after_count - macos_n3_console_before_count);
    write_string("/");
    write_dec_u32(macos_n3_console_after_bytes - macos_n3_console_before_bytes);
    write_string(" strlen ");
    write_dec_u32((u32)macos_n3_strlen_result.value);
    write_string(" mem ");
    write_hex_u64(macos_n3_malloc_result.value);
    write_string("/");
    write_hex_u64(macos_n3_realloc_result.value);
    write_string("/");
    write_dec_u32(macos_n3_copied_match);
    write_string("/");
    write_dec_u32(macos_n3_free_result.error);
    write_string(" mmap ");
    write_hex_u64(macos_n3_mmap_result.value);
    write_string("/");
    write_dec_u32(macos_n3_mmap_present);
    write_string("/");
    write_hex_u32(macos_n3_mprotect_prot);
    write_string("/");
    write_hex_u64(macos_n3_munmap_result.value);
    write_string(" open ");
    write_hex_u64(macos_n3_open_result.value);
    write_string("/");
    write_hex_u64(macos_n3_close_result.value);
    write_string(" clock ");
    write_hex_u64(macos_n3_clock_result.value);
    write_string("/");
    write_dec_u32(macos_n3_time_written);
    write_string(" bad ");
    write_dec_u32(macos_n3_bad_result.error);
    write_string(" counts ");
    write_dec_u32(macos_n3_load_delta);
    write_string("/");
    write_dec_u32(macos_n3_call_delta);
    write_string("/");
    write_dec_u32(macos_n3_bridge_delta);
    write_string("/");
    write_dec_u32(macos_n3_memory_delta);
    write_string("/");
    write_dec_u32(macos_n3_denial_delta);
    write_string("/");
    write_dec_u32(macos_n3_fault_delta);
    write_string(" audit ");
    write_dec_u32(macos_n3_audit_before);
    write_string("/");
    write_dec_u32(macos_n3_audit_after);
    write_string(" last ");
    write_dec_u32(macos_n3_last_symbol);
    write_string("/");
    write_dec_u32(macos_n3_last_error);
    write_string("/");
    write_hex_u64(macos_n3_last_result);
    write_string(" cleanup ");
    write_dec_u32(macos_n3_release_shim);
    write_string("/");
    write_dec_u32(macos_n3_unmap_buffer);
    write_string("/");
    write_dec_u32(macos_n3_fd_release);
    write_string("/");
    write_dec_u32(macos_n3_persona_release);
    write_string("/");
    write_dec_u32(macos_n3_audit_release);
    write_string("/");
    write_dec_u32(macos_n3_vma_release);
    write_string("/");
    write_dec_u32(macos_n3_clone_release);
    write_string("/");
    write_dec_u32(macos_n3_cleanup);
    write_string(" positive ");
    write_dec_u32(macos_n3_positive);
    write_line("");
    write_string("[x64] macos-dyld-N4 load ");
    write_dec_u32(macos_n4_load);
    write_string("/");
    write_dec_u32(macos_n4_bad_load);
    write_string(" err ");
    write_dec_u32(macos_n4_load_result.error);
    write_string("/");
    write_dec_u32(macos_n4_bad_load_result.error);
    write_string(" syms ");
    write_dec_u32(macos_n4_symbol_count);
    write_string("/");
    write_dec_u32(macos_n4_resolved_count);
    write_string(" addrs ");
    write_hex_u64(macos_n4_stub_addr);
    write_string("/");
    write_hex_u64(macos_n4_get_name_addr);
    write_string("/");
    write_hex_u64(macos_n4_image_count_addr);
    write_string("/");
    write_hex_u64(macos_n4_missing_addr);
    write_string(" map ");
    write_dec_u32(macos_n4_load_result.mapped_count);
    write_string("/");
    write_dec_u32(macos_n4_text_present);
    write_string("/");
    write_dec_u32(macos_n4_rodata_present);
    write_string("/");
    write_dec_u32(macos_n4_buffer_map);
    write_string(" prot ");
    write_hex_u32(macos_n4_load_result.text_protection);
    write_string("/");
    write_hex_u32(macos_n4_load_result.rodata_protection);
    write_string(" checks ");
    write_hex_u32(macos_n4_load_result.text_checksum);
    write_string("/");
    write_hex_u32(macos_n4_load_result.rodata_checksum);
    write_string("/");
    write_hex_u32(macos_n4_load_result.name_checksum);
    write_string(" bind ");
    write_hex_u64(macos_n4_missing_bind_result.slot);
    write_string("/");
    write_hex_u64(macos_n4_binder_result.value);
    write_string("/");
    write_hex_u64(macos_n4_slot_after);
    write_string("/");
    write_dec_u32(macos_n4_binder_result.byte_count);
    write_string("/");
    write_hex_u32(macos_n4_binder_result.checksum);
    write_string(" images ");
    write_dec_u32((u32)macos_n4_count_result.value);
    write_string("/");
    write_hex_u64(macos_n4_name_result.value);
    write_string("/");
    write_dec_u32(macos_n4_name_result.byte_count);
    write_string("/");
    write_dec_u32(macos_n4_name_prefix);
    write_string("/");
    write_hex_u32(macos_n4_name_result.checksum);
    write_string(" bad ");
    write_dec_u32(macos_n4_missing_bind_result.error);
    write_string("/");
    write_dec_u32(macos_n4_bad_call_result.error);
    write_string(" counts ");
    write_dec_u32(macos_n4_load_delta);
    write_string("/");
    write_dec_u32(macos_n4_call_delta);
    write_string("/");
    write_dec_u32(macos_n4_lazy_delta);
    write_string("/");
    write_dec_u32(macos_n4_image_delta);
    write_string("/");
    write_dec_u32(macos_n4_denial_delta);
    write_string("/");
    write_dec_u32(macos_n4_fault_delta);
    write_string(" audit ");
    write_dec_u32(macos_n4_audit_before);
    write_string("/");
    write_dec_u32(macos_n4_audit_after);
    write_string(" last ");
    write_dec_u32(macos_dyld64_last_symbol());
    write_string("/");
    write_dec_u32(macos_dyld64_last_error());
    write_string("/");
    write_hex_u64(macos_dyld64_last_result());
    write_string(" cleanup ");
    write_dec_u32(macos_n4_release_shim);
    write_string("/");
    write_dec_u32(macos_n4_unmap_buffer);
    write_string("/");
    write_dec_u32(macos_n4_persona_release);
    write_string("/");
    write_dec_u32(macos_n4_audit_release);
    write_string("/");
    write_dec_u32(macos_n4_vma_release);
    write_string("/");
    write_dec_u32(macos_n4_clone_release);
    write_string("/");
    write_dec_u32(macos_n4_cleanup);
    write_string(" positive ");
    write_dec_u32(macos_n4_positive);
    write_line("");
    write_string("[x64] macos-cf-N5 load ");
    write_dec_u32(macos_n5_load);
    write_string("/");
    write_dec_u32(macos_n5_bad_load);
    write_string(" lib ");
    write_dec_u32(macos_n5_libsystem_load);
    write_string(" err ");
    write_dec_u32(macos_n5_load_result.error);
    write_string("/");
    write_dec_u32(macos_n5_bad_load_result.error);
    write_string(" syms ");
    write_dec_u32(macos_n5_symbol_count);
    write_string("/");
    write_dec_u32(macos_n5_resolved_count);
    write_string(" addrs ");
    write_hex_u64(macos_n5_allocator_addr);
    write_string("/");
    write_hex_u64(macos_n5_create_addr);
    write_string("/");
    write_hex_u64(macos_n5_get_addr);
    write_string("/");
    write_hex_u64(macos_n5_show_addr);
    write_string("/");
    write_hex_u64(macos_n5_missing_addr);
    write_string(" map ");
    write_dec_u32(macos_n5_load_result.mapped_count);
    write_string("/");
    write_dec_u32(macos_n5_text_present);
    write_string("/");
    write_dec_u32(macos_n5_rodata_present);
    write_string("/");
    write_dec_u32(macos_n5_buffer_map);
    write_string(" prot ");
    write_hex_u32(macos_n5_load_result.text_protection);
    write_string("/");
    write_hex_u32(macos_n5_load_result.rodata_protection);
    write_string(" checks ");
    write_hex_u32(macos_n5_load_result.text_checksum);
    write_string("/");
    write_hex_u32(macos_n5_load_result.rodata_checksum);
    write_string("/");
    write_hex_u32(macos_n5_load_result.name_checksum);
    write_string(" alloc ");
    write_hex_u64(macos_n5_allocator_result.value);
    write_string(" create ");
    write_hex_u64(macos_n5_create_result.value);
    write_string("/");
    write_dec_u32(macos_n5_create_result.byte_count);
    write_string("/");
    write_hex_u32(macos_n5_create_result.checksum);
    write_string(" retain ");
    write_hex_u64(macos_n5_retain_result.value);
    write_string("/");
    write_dec_u32(macos_n5_retain_result.byte_count);
    write_string(" get ");
    write_dec_u32((u32)macos_n5_get_result.value);
    write_string("/");
    write_dec_u32(macos_n5_get_result.byte_count);
    write_string("/");
    write_dec_u32(macos_n5_output_match);
    write_string("/");
    write_dec_u32(macos_n5_output_nul);
    write_string(" show ");
    write_dec_u32((u32)macos_n5_show_result.value);
    write_string("/");
    write_dec_u32(macos_n5_console_after_count - macos_n5_console_before_count);
    write_string("/");
    write_dec_u32(macos_n5_console_after_bytes - macos_n5_console_before_bytes);
    write_string(" release ");
    write_dec_u32((u32)macos_n5_release1_result.value);
    write_string("/");
    write_dec_u32((u32)macos_n5_release2_result.value);
    write_string(" live ");
    write_dec_u32(macos_n5_live_after_create);
    write_string("/");
    write_dec_u32(macos_n5_live_after_retain);
    write_string("/");
    write_dec_u32(macos_n5_live_after_release1);
    write_string("/");
    write_dec_u32(macos_n5_live_after_release2);
    write_string(" bad ");
    write_dec_u32(macos_n5_bad_result.error);
    write_string(" counts ");
    write_dec_u32(macos_n5_load_delta);
    write_string("/");
    write_dec_u32(macos_n5_call_delta);
    write_string("/");
    write_dec_u32(macos_n5_create_delta);
    write_string("/");
    write_dec_u32(macos_n5_get_delta);
    write_string("/");
    write_dec_u32(macos_n5_show_delta);
    write_string("/");
    write_dec_u32(macos_n5_retain_delta);
    write_string("/");
    write_dec_u32(macos_n5_release_delta);
    write_string("/");
    write_dec_u32(macos_n5_denial_delta);
    write_string("/");
    write_dec_u32(macos_n5_fault_delta);
    write_string("/");
    write_dec_u32(macos_n5_scratch_delta);
    write_string("/");
    write_dec_u32(macos_n5_shim_call_delta);
    write_string("/");
    write_dec_u32(macos_n5_shim_bridge_delta);
    write_string(" audit ");
    write_dec_u32(macos_n5_audit_before);
    write_string("/");
    write_dec_u32(macos_n5_audit_after);
    write_string(" last ");
    write_dec_u32(macos_cf64_last_symbol());
    write_string("/");
    write_dec_u32(macos_cf64_last_error());
    write_string("/");
    write_hex_u64(macos_cf64_last_result());
    write_string(" cleanup ");
    write_dec_u32(macos_n5_release_cf);
    write_string("/");
    write_dec_u32(macos_n5_release_shim);
    write_string("/");
    write_dec_u32(macos_n5_unmap_buffer);
    write_string("/");
    write_dec_u32(macos_n5_fd_release);
    write_string("/");
    write_dec_u32(macos_n5_persona_release);
    write_string("/");
    write_dec_u32(macos_n5_audit_release);
    write_string("/");
    write_dec_u32(macos_n5_vma_release);
    write_string("/");
    write_dec_u32(macos_n5_clone_release);
    write_string("/");
    write_dec_u32(macos_n5_cleanup);
    write_string(" positive ");
    write_dec_u32(macos_n5_positive);
    write_line("");
#endif
#endif /* LIMITLESS_SCAFFOLD_MACOS_OUTPUT */

#if !defined(LIMITLESS_SCAFFOLD_UNITY)
void limitless_scaffold_macos_anchor(void) {}
#endif
