#ifndef LIMITLESS_BOOT_DIAG_X64_H
#define LIMITLESS_BOOT_DIAG_X64_H

#include "types.h"

#define BOOT_DIAG64_TIMING_XHCI_INIT 0u
#define BOOT_DIAG64_TIMING_BOOT_DIAG 1u
#define BOOT_DIAG64_TIMING_NVME_PROBE 2u
#define BOOT_DIAG64_TIMING_DISPLAY_INIT 3u
#define BOOT_DIAG64_TIMING_I2C_HID_INIT 4u
#define BOOT_DIAG64_TIMING_TIMER_WAIT 5u
#define BOOT_DIAG64_TIMING_KEYBOARD_WAIT 6u
#define BOOT_DIAG64_TIMING_MOUSE_WAIT 7u
#define BOOT_DIAG64_TIMING_LOGIN 8u
#define BOOT_DIAG64_TIMING_LOCK_PROBE 9u
#define BOOT_DIAG64_TIMING_WM_PROBE 10u
#define BOOT_DIAG64_TIMING_DESKTOP_PROBE 11u
#define BOOT_DIAG64_TIMING_VIRTIO_NET_INIT 12u
#define BOOT_DIAG64_TIMING_PIT_TO_SHELL 13u
#define BOOT_DIAG64_TIMING_COUNT 14u

u32 boot_diag64_timing_ticks(u32 index);
u32 boot_diag64_timer_wait_spin_budget(void);

#endif
