#ifndef LIMITLESS_RUNTIME_IMAGE_X64_H
#define LIMITLESS_RUNTIME_IMAGE_X64_H

#include "types.h"

#define RUNTIME64_TRANSFER_IMAGE_BYTES 0x00004000u
#define RUNTIME64_TRANSFER_ENTRY_RESULT 0x36534F4Cu
#define RUNTIME64_TRANSFER_USER_ENTRY_OFFSET 0x00000010u
#define RUNTIME64_TRANSFER_USER_SYSCALL_RESULT 0x36534F4Cu
#define RUNTIME64_TRANSFER_USER_PREEMPT_ENTRY_OFFSET 0x00000040u
#define RUNTIME64_TRANSFER_USER_PREEMPT_RESULT 0x5052454Du
#define RUNTIME64_TRANSFER_USER_PREEMPT_SPIN_COUNT 0x00400000u
#define RUNTIME64_TRANSFER_USER_SWITCH_SOURCE_OFFSET 0x00000080u
#define RUNTIME64_TRANSFER_USER_SWITCH_TARGET_OFFSET 0x000000C0u
#define RUNTIME64_TRANSFER_USER_SWITCH_RESULT 0x53574348u
#define RUNTIME64_TRANSFER_USER_SWITCH_TIMEOUT_RESULT 0x544F5554u
#define RUNTIME64_TRANSFER_USER_SWITCH_SPIN_COUNT 0x00080000u
#define RUNTIME64_TRANSFER_USER_SWITCH_TARGET_STACK_DELTA 0x00000400u
#define RUNTIME64_TRANSFER_USER_RUNQUEUE_SOURCE_OFFSET 0x00000100u
#define RUNTIME64_TRANSFER_USER_RUNQUEUE_TARGET_OFFSET 0x00000140u
#define RUNTIME64_TRANSFER_USER_RUNQUEUE_SOURCE_RESULT 0x52514131u
#define RUNTIME64_TRANSFER_USER_RUNQUEUE_TARGET_RESULT 0x52514232u
#define RUNTIME64_TRANSFER_USER_RUNQUEUE_SPIN_COUNT 0x00080000u
#define RUNTIME64_TRANSFER_USER_RUNQUEUE_TARGET_STACK_DELTA 0x00000800u
#define RUNTIME64_TRANSFER_USER_FS_PROBE_OFFSET 0x00000180u
#define RUNTIME64_TRANSFER_USER_FS_RESULT 0x46535233u
#define RUNTIME64_TRANSFER_USER_FS_ERROR_RESULT 0x46455252u
#define RUNTIME64_TRANSFER_USER_FS_READ_BYTES 0x00000020u
#define RUNTIME64_TRANSFER_USER_FS_README_PATH_OFFSET 0x00000240u
#define RUNTIME64_TRANSFER_USER_FS_README_PATH_LENGTH 10u
#define RUNTIME64_TRANSFER_USER_CLI_PROBE_OFFSET 0x00000280u
#define RUNTIME64_TRANSFER_USER_CLI_RESULT 0x434C4931u
#define RUNTIME64_TRANSFER_USER_CLI_ERROR_RESULT 0x43455252u
#define RUNTIME64_TRANSFER_USER_CLI_PROMPT_OFFSET 0x00000360u
#define RUNTIME64_TRANSFER_USER_CLI_PROMPT_LENGTH 28u
#define RUNTIME64_TRANSFER_USER_CLI_NEWLINE_OFFSET 0x00000380u
#define RUNTIME64_TRANSFER_USER_CLI_NEWLINE_LENGTH 1u
#define RUNTIME64_TRANSFER_USER_INPUT_CLI_PROMPT_OFFSET 0x00000390u
#define RUNTIME64_TRANSFER_USER_INPUT_CLI_PROMPT_LENGTH 14u
#define RUNTIME64_TRANSFER_USER_INPUT_CLI_PROBE_OFFSET 0x000003C0u
#define RUNTIME64_TRANSFER_USER_INPUT_CLI_RESULT 0x49434C31u
#define RUNTIME64_TRANSFER_USER_INPUT_CLI_ERROR_RESULT 0x49455252u
#define RUNTIME64_TRANSFER_USER_INPUT_CLI_COMMAND_BYTES 14u
#define RUNTIME64_TRANSFER_USER_APPS_PATH_OFFSET 0x00000520u
#define RUNTIME64_TRANSFER_USER_APPS_PATH_LENGTH 4u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_PROBE_OFFSET 0x00000540u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_RESULT 0x53484C31u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_ERROR_RESULT 0x53455252u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_COMMAND_BYTES 167u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_COMMAND_CAPACITY 32u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_EXPECTED_COMMANDS 19u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_EXPECTED_UNKNOWNS 2u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_HELP_COMMAND_BYTES 4u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_HELP_LS_COMMAND_BYTES 7u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_HELP_CAT_COMMAND_BYTES 8u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_HELP_STAT_COMMAND_BYTES 9u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_HELP_MKDIR_COMMAND_BYTES 10u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_HELP_WRITE_COMMAND_BYTES 10u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_APPS_COMMAND_BYTES 4u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_PWD_COMMAND_BYTES 3u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_LS_ROOT_COMMAND_BYTES 4u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_LS_COMMAND_BYTES 7u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_INFO_LS_COMMAND_BYTES 7u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_INFO_CAT_COMMAND_BYTES 8u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_INFO_STAT_COMMAND_BYTES 9u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_INFO_MKDIR_COMMAND_BYTES 10u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_INFO_WRITE_COMMAND_BYTES 10u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_CAT_SHELL_COMMAND_BYTES 13u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_CAT_COMMAND_BYTES 14u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_STAT_COMMAND_BYTES 15u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_UNKNOWN_COMMAND_BYTES 9u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_HELP_BYTES 46u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_HELP_LS_BYTES 60u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_HELP_CAT_BYTES 33u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_HELP_STAT_BYTES 46u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_HELP_MKDIR_BYTES 39u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_HELP_WRITE_BYTES 44u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_APPS_INDEX_BYTES 129u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_LS_APP_BYTES 79u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_CAT_APP_BYTES 52u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_STAT_APP_BYTES 65u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_MKDIR_APP_BYTES 58u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_WRITE_APP_BYTES 64u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_INFO_LS_OUTPUT_BYTES 96u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_INFO_CAT_OUTPUT_BYTES 99u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_INFO_STAT_OUTPUT_BYTES 102u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_INFO_MKDIR_OUTPUT_BYTES 105u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_INFO_WRITE_OUTPUT_BYTES 113u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_PWD_BYTES 1u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_ROOT_LIST_BYTES 52u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_LIST_BYTES 63u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_CAT_BYTES 32u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_STAT_BYTES 19u
#define RUNTIME64_TRANSFER_USER_SHELL_STREAM_UNKNOWN_MESSAGE_BYTES 15u
#define RUNTIME64_TRANSFER_USER_KEYBOARD_PROBE_OFFSET 0x00002D80u
#define RUNTIME64_TRANSFER_USER_KEYBOARD_RESULT 0x4B455931u
#define RUNTIME64_TRANSFER_USER_KEYBOARD_ERROR_RESULT 0x4B455252u
#define RUNTIME64_TRANSFER_USER_KEYBOARD_READ_BYTES 2u
#define RUNTIME64_TRANSFER_USER_HARDWARE_SHELL_PROBE_OFFSET 0x00003000u
#define RUNTIME64_TRANSFER_USER_HARDWARE_SHELL_RESULT 0x48534831u
#define RUNTIME64_TRANSFER_USER_HARDWARE_SHELL_ERROR_RESULT 0x48534552u
#define RUNTIME64_TRANSFER_USER_HARDWARE_SHELL_EXPECTED_COMMANDS 13u
#define RUNTIME64_TRANSFER_USER_HARDWARE_SHELL_REQUIRED_FLAGS 0x00000FFFu
#define RUNTIME64_TRANSFER_USER_HARDWARE_SHELL_EXIT_COMMAND_BYTES 4u
#define RUNTIME64_TRANSFER_USER_HARDWARE_SHELL_BYE_BYTES 4u
#define RUNTIME64_TRANSFER_USER_SECOND_PAGE_OFFSET 0x00001ED0u
#define RUNTIME64_TRANSFER_USER_SECOND_PAGE_RESULT 0x32504752u
#define RUNTIME64_TRANSFER_USER_SECOND_PAGE_NOTE_PATH_BYTES 11u
#define RUNTIME64_TRANSFER_USER_SECOND_PAGE_NOTE_BYTES 15u

const void *runtime64_transfer_image_base(void);
u32 runtime64_transfer_image_size(void);
u32 runtime64_transfer_entry_result(void);
u32 runtime64_transfer_user_entry_offset(void);
u32 runtime64_transfer_user_syscall_result(void);
u32 runtime64_transfer_user_preempt_entry_offset(void);
u32 runtime64_transfer_user_preempt_result(void);
u32 runtime64_transfer_user_switch_source_offset(void);
u32 runtime64_transfer_user_switch_target_offset(void);
u32 runtime64_transfer_user_switch_result(void);
u32 runtime64_transfer_user_switch_target_stack_delta(void);
u32 runtime64_transfer_user_runqueue_source_offset(void);
u32 runtime64_transfer_user_runqueue_target_offset(void);
u32 runtime64_transfer_user_runqueue_source_result(void);
u32 runtime64_transfer_user_runqueue_target_result(void);
u32 runtime64_transfer_user_runqueue_target_stack_delta(void);
u32 runtime64_transfer_user_fs_probe_offset(void);
u32 runtime64_transfer_user_fs_result(void);
u32 runtime64_transfer_user_fs_error_result(void);
u32 runtime64_transfer_user_fs_read_bytes(void);
u32 runtime64_transfer_user_cli_probe_offset(void);
u32 runtime64_transfer_user_cli_result(void);
u32 runtime64_transfer_user_cli_error_result(void);
u32 runtime64_transfer_user_cli_prompt_length(void);
u32 runtime64_transfer_user_input_cli_probe_offset(void);
u32 runtime64_transfer_user_input_cli_result(void);
u32 runtime64_transfer_user_input_cli_error_result(void);
u32 runtime64_transfer_user_input_cli_prompt_length(void);
u32 runtime64_transfer_user_input_cli_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_probe_offset(void);
u32 runtime64_transfer_user_shell_stream_result(void);
u32 runtime64_transfer_user_shell_stream_error_result(void);
u32 runtime64_transfer_user_shell_stream_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_command_capacity(void);
u32 runtime64_transfer_user_shell_stream_expected_commands(void);
u32 runtime64_transfer_user_shell_stream_expected_unknowns(void);
u32 runtime64_transfer_user_shell_stream_help_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_help_ls_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_help_cat_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_help_stat_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_help_mkdir_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_help_write_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_apps_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_pwd_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_ls_root_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_ls_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_info_ls_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_info_cat_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_info_stat_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_info_mkdir_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_info_write_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_cat_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_stat_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_unknown_command_bytes(void);
u32 runtime64_transfer_user_shell_stream_help_bytes(void);
u32 runtime64_transfer_user_shell_stream_help_ls_bytes(void);
u32 runtime64_transfer_user_shell_stream_help_cat_bytes(void);
u32 runtime64_transfer_user_shell_stream_help_stat_bytes(void);
u32 runtime64_transfer_user_shell_stream_help_mkdir_bytes(void);
u32 runtime64_transfer_user_shell_stream_help_write_bytes(void);
u32 runtime64_transfer_user_shell_stream_apps_index_bytes(void);
u32 runtime64_transfer_user_shell_stream_ls_app_bytes(void);
u32 runtime64_transfer_user_shell_stream_cat_app_bytes(void);
u32 runtime64_transfer_user_shell_stream_stat_app_bytes(void);
u32 runtime64_transfer_user_shell_stream_mkdir_app_bytes(void);
u32 runtime64_transfer_user_shell_stream_write_app_bytes(void);
u32 runtime64_transfer_user_shell_stream_info_ls_output_bytes(void);
u32 runtime64_transfer_user_shell_stream_info_cat_output_bytes(void);
u32 runtime64_transfer_user_shell_stream_info_stat_output_bytes(void);
u32 runtime64_transfer_user_shell_stream_info_mkdir_output_bytes(void);
u32 runtime64_transfer_user_shell_stream_info_write_output_bytes(void);
u32 runtime64_transfer_user_shell_stream_pwd_bytes(void);
u32 runtime64_transfer_user_shell_stream_root_list_bytes(void);
u32 runtime64_transfer_user_shell_stream_list_bytes(void);
u32 runtime64_transfer_user_shell_stream_cat_bytes(void);
u32 runtime64_transfer_user_shell_stream_stat_bytes(void);
u32 runtime64_transfer_user_shell_stream_unknown_message_bytes(void);
u32 runtime64_transfer_user_keyboard_probe_offset(void);
u32 runtime64_transfer_user_keyboard_result(void);
u32 runtime64_transfer_user_keyboard_error_result(void);
u32 runtime64_transfer_user_keyboard_read_bytes(void);
u32 runtime64_transfer_user_hardware_shell_probe_offset(void);
u32 runtime64_transfer_user_hardware_shell_result(void);
u32 runtime64_transfer_user_hardware_shell_error_result(void);
u32 runtime64_transfer_user_hardware_shell_expected_commands(void);
u32 runtime64_transfer_user_hardware_shell_required_flags(void);
u32 runtime64_transfer_user_hardware_shell_exit_command_bytes(void);
u32 runtime64_transfer_user_hardware_shell_bye_bytes(void);
u32 runtime64_transfer_user_second_page_offset(void);
u32 runtime64_transfer_user_second_page_result(void);
u32 runtime64_transfer_user_second_page_note_path_bytes(void);
u32 runtime64_transfer_user_second_page_note_bytes(void);

#endif
