#ifndef LIMITLESS_SYSCALL_H
#define LIMITLESS_SYSCALL_H

#include "types.h"

enum syscall_number
{
    SYSCALL_GET_UPTIME_TICKS = 0,
    SYSCALL_GET_IPC_ENDPOINT_COUNT = 1,
    SYSCALL_GET_FREE_MEMORY_KIB = 2,
    SYSCALL_GET_ASSISTANT_POLICY_FLAGS = 3,
    SYSCALL_GET_SCHEDULER_TASK_COUNT = 4,
    SYSCALL_GET_FREE_FRAME_COUNT = 5,
    SYSCALL_GET_MAPPED_MEMORY_MIB = 6,
    SYSCALL_GET_SERVICE_COUNT = 7,
    SYSCALL_GET_DENIED_IPC_COUNT = 8,
    SYSCALL_GET_USER_SYSCALL_COUNT = 9,
    SYSCALL_GET_USER_PROCESS_COUNT = 10,
    SYSCALL_GET_USER_YIELD_COUNT = 11,
    SYSCALL_GET_USER_PREEMPT_COUNT = 12,
    SYSCALL_USER_SLEEP_TICKS = 13,
    SYSCALL_USER_YIELD = 14,
    SYSCALL_GET_USER_SLEEP_COUNT = 15,
    SYSCALL_GET_USER_IPC_WAIT_COUNT = 16,
    SYSCALL_GET_USER_IPC_MESSAGE_COUNT = 17,
    SYSCALL_USER_POLICY_REQUEST = 18,
    SYSCALL_USER_WAIT_IPC = 19,
    SYSCALL_GET_USER_IPC_SEND_COUNT = 20,
    SYSCALL_GET_USER_IPC_DENIED_COUNT = 21,
    SYSCALL_USER_SEND_IPC = 22,
    SYSCALL_USER_REGISTER_ENDPOINT = 23,
    SYSCALL_GET_USER_ENDPOINT_COUNT = 24,
    SYSCALL_USER_LOOKUP_ENDPOINT = 25,
    SYSCALL_USER_LOOKUP_SERVICE_ENDPOINT = 26,
    SYSCALL_USER_REVOKE_CAPABILITY = 27,
    SYSCALL_USER_LOOKUP_ENDPOINT_CLASS = 28,
    SYSCALL_USER_DELEGATE_CAPABILITY = 29,
    SYSCALL_USER_REGISTER_SHARED_BUFFER = 30,
    SYSCALL_USER_READ_SHARED_BUFFER = 31,
    SYSCALL_USER_WRITE_SHARED_BUFFER = 32,
    SYSCALL_USER_EXIT = 33,
    SYSCALL_USER_CONSOLE_WRITE = 34,
    SYSCALL_USER_FS_OPEN = 35,
    SYSCALL_USER_FS_LIST = 36,
    SYSCALL_USER_FS_READ = 37,
    SYSCALL_USER_FS_CREATE = 38,
    SYSCALL_USER_FS_WRITE = 39,
    SYSCALL_USER_LAUNCH_EXECUTABLE = 40,
    SYSCALL_USER_INPUT_READ = 41,
    SYSCALL_USER_FS_STAT = 42,
    SYSCALL_USER_FS_RENAME = 43,
    SYSCALL_USER_FS_DELETE = 44,
    SYSCALL_USER_WAIT_PROCESS = 45,
    SYSCALL_USER_FS_MOVE = 46
};

enum assistant_policy_flag
{
    ASSISTANT_POLICY_REQUIRE_CONSENT = 0x00000001,
    ASSISTANT_POLICY_AUDIT_ACTIONS = 0x00000002,
    ASSISTANT_POLICY_SEALED_CORE = 0x00000004
};

u32 syscall_dispatch(u32 number, u32 arg0, u32 arg1, u32 arg2);

static inline u32 syscall_invoke(u32 number, u32 arg0, u32 arg1, u32 arg2)
{
    u32 result;

    __asm__ __volatile__(
        "int $0x80"
        : "=a"(result)
        : "a"(number), "b"(arg0), "c"(arg1), "d"(arg2)
        : "memory");

    return result;
}

#endif
